service: voting-api

useDotenv: true

package:
  individually: true

custom:
  prune:
    automatic: true
    number: 3
  bundle:
    packager: yarn

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  region: ap-east-1
  httpApi:
    cors: true

plugins:
  - serverless-offline
  - serverless-dotenv-plugin

functions:
  create-tables:
    handler: create_db/create-tables.handler
    memorySize: 256
    timeout: 30
  get-campaigns:
    handler: functions/get-campaigns.handler
    memorySize: 256
    timeout: 30
    events:
      - http:
          path: get-campaigns
          method: get
          cors: true
  get-candidates:
    handler: functions/get-candidates.handler
    memorySize: 256
    timeout: 30
    events:
      - http:
          path: get-candidates/{id}
          method: get
          cors: true
          request:
              parameter:
                id: true
  get-result:
    handler: functions/get-result.handler
    memorySize: 256
    timeout: 30
    events:
      - http:
          path: get-result/{id}
          method: get
          cors: true
          request:
              parameter:
                id: true
  vote:
    handler: functions/vote.handler
    memorySize: 256
    timeout: 30
    events:
      - http:
          path: vote
          method: post
          cors: true
